### ISSUE TITLE
Multiple results returned for rear-port-templates wheras the API call returns a single record

### ISSUE THREAD

**Issue by jifox** [nautobot/pynautobot#15]
I've tried to select a rear-port-template entry with pynautobot.

Nautobot: fbe10eeac2ef (v1.0.1b1)
pynautobot: pynautobot==1.0.2

In debug console I've checked the following:

```bash
### Lookup manufacturer
mymanufacturer = nbot.dcim.manufacturers.get(slug="schrack")

mymanufacturer.id
'b6bf84af-4e40-46b4-8ba2-d9f094a9f9f3'

mymanufacturer.slug
'schrack'


###  Lookup device-type
mydevicetype = nbot.dcim.device_types.get(model="LWL-12xLC-FD", 

self.mydevicetype.id
'b363a795-d37c-4449-bc19-f9e94321adc9'

self.mydevicetype.model
'LWL-12xLC-FD'


### Select rear-port-template
nbot.dcim.rear_port_templates.get(name="rear1", device_type_id="b363a795-d37c-4449-bc19-f9e94321adc9")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ansible/devel/nautobot-transfer/lib/python3.8/site-packages/pynautobot/core/endpoint.py", line 139, in get
    raise ValueError(
ValueError: get() returned more than one result. Check that the kwarg(s) passed are valid for this endpoint or use filter() or all() instead.

### Use filter 
nbot.dcim.rear_port_templates.filter(name="rear1", device_type_id="b363a795-d37c-4449-bc19-f9e94321adc9")
[rear1, rear1]

### details for first entry that should have been returned with get()
nbot.dcim.rear_port_templates.filter(name="rear1", device_type_id="b363a795-d37c-4449-bc19-f9e94321adc9")[0]["device_type"]
{'display': 'Schrack LWL-12xLC-FD', 'id': 'b363a795-d37c-4449-b...e94321adc9', 'manufacturer': {'display': 'Schrack', 'id': 'b6bf84af-4e40-46b4-8...f094a9f9f3', 'name': 'Schrack', 'slug': 'schrack', 'url': 'http://scvpconf01:80...094a9f9f3/'}, 'model': 'LWL-12xLC-FD', 'slug': 'lwl-12xlc-fd', 'url': 'http://scvpconf01:80...94321adc9/'}

### details for 2nd entry
nbot.dcim.rear_port_templates.filter(name="rear1", device_type_id="b363a795-d37c-4449-bc19-f9e94321adc9")[1]["device_type"]
{'display': 'Schrack LWL-4xLC-FD', 'id': 'fb84cace-178e-403b-8...7c014666cb', 'manufacturer': {'display': 'Schrack', 'id': 'b6bf84af-4e40-46b4-8...f094a9f9f3', 'name': 'Schrack', 'slug': 'schrack', 'url': 'http://scvpconf01:80...094a9f9f3/'}, 'model': 'LWL-4xLC-FD', 'slug': 'lwl-4xlc-fd', 'url': 'http://scvpconf01:80...c014666cb/'}
```

When using the API with this values, only one record is returned.

![image](https://user-images.githubusercontent.com/8406301/117811345-b8aecc80-b260-11eb-8b85-b9a6c26b059d.png)

**Comment by jifox** [comment]
I*m using as a workaround:

```python
        try:
            return self.endpoint.get(name=current_row["name"], device_type_id=self.mydevicetype.id)  # type: ignore
        except ValueError:
            # Handle issue #15 (https://github.com/nautobot/pynautobot/issues/15)
            res = self.endpoint.filter(name=current_row["name"], device_type_id=self.mydevicetype.id)  # type: ignore
            for rearp in res:
                if rearp["name"] == current_row["name"] and rearp["device_type"]["id"] == self.mydevicetype.id:  # type: ignore
                    return rearp
        return None

```

**Comment by FragmentedPacket** [comment]
@jifox You're passing in a wrong query filter. Look at what you're passing in and what you're showing in the API request URL.

```python
>>> from pynautobot import api
>>> nb = api("http://localhost:8000", "0123456789abcdef0123456789abcdef01234567")
>>> dt = nb.dcim.device_types.get(slug="c9300-24")
>>> nb.dcim.rear_port_templates.all()
[rear1, rear1]
>>> nb.dcim.rear_port_templates.filter(name="rear1", device_type_id=dt.id)
[rear1, rear1]
>>> nb.dcim.rear_port_templates.get(name="rear1", device_type_id=dt.id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myohman/cloned-repos/pynautobot/pynautobot/core/endpoint.py", line 139, in get
    raise ValueError(
ValueError: get() returned more than one result. Check that the kwarg(s) passed are valid for this endpoint or use filter() or all() instead.
>>> nb.dcim.rear_port_templates.get(name="rear1", devicetype_id=dt.id)
rear1
```

It should be `devicetype_id` instead of `device_type_id`.
