### ISSUE TITLE
Pynautobot fails when getting device without a name

### ISSUE THREAD

**Issue by scetron** [nautobot/pynautobot#34]
Version: 1.0.4

When attempting to get an unnamed device, pynautobot throws a series of errors:

```
 nb.dcim.devices.get('8d1ff4f5-fa9f-5bef-9ae3-79fb153bd88b')
Traceback (most recent call last):
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10ba5b7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nautobot', port=8080): Max retries exceeded with url: /api/dcim/devices/8d1ff4f5-fa9f-5bef-9ae3-79fb153bd88b/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ba5b7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/response.py", line 211, in __repr__
    return str(self)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/response.py", line 208, in __str__
    return getattr(self, "name", None) or getattr(self, "label", None) or ""
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/response.py", line 187, in __getattr__
    if self.full_details():
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/response.py", line 302, in full_details
    self._parse_values(req.get())
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/query.py", line 295, in get
    return req_all()
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/query.py", line 253, in req_all
    req = self._make_call(add_params=add_params)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/query.py", line 211, in _make_call
    req = getattr(self.http_session, verb)(url_override or self.url, headers=headers, params=params, json=data)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='nautobot', port=8080): Max retries exceeded with url: /api/dcim/devices/8d1ff4f5-fa9f-5bef-9ae3-79fb153bd88b/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ba5b7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
>>> nb.dcim.devices.filter(site="ld8-pc-broa", name=None)
Traceback (most recent call last):
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10ba557f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nautobot', port=8080): Max retries exceeded with url: /api/dcim/devices/8d1ff4f5-fa9f-5bef-9ae3-79fb153bd88b/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ba557f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/response.py", line 211, in __repr__
    return str(self)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/response.py", line 208, in __str__
    return getattr(self, "name", None) or getattr(self, "label", None) or ""
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/response.py", line 187, in __getattr__
    if self.full_details():
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/response.py", line 302, in full_details
    self._parse_values(req.get())
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/query.py", line 295, in get
    return req_all()
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/query.py", line 253, in req_all
    req = self._make_call(add_params=add_params)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/pynautobot/core/query.py", line 211, in _make_call
    req = getattr(self.http_session, verb)(url_override or self.url, headers=headers, params=params, json=data)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/stcorry/Library/Caches/pypoetry/virtualenvs/network-importer-tLw0PxIN-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='nautobot', port=8080): Max retries exceeded with url: /api/dcim/devices/8d1ff4f5-fa9f-5bef-9ae3-79fb153bd88b/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ba557f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))```

**Comment by scetron** [comment]
The above traceback may have been also caused by a webserver issue, as it is not showing up when I attempt to recreate this locally. However, when a device has no name, I'd expect the UUID to be shown (like in the GUI) instead of an empty string which appears to be the behavior when an object/record has no name or label.

**Comment by FragmentedPacket** [comment]
Seems like the output within the issue was more of a connectivity issue, but the real issue is the lack of str representation.

This should be straight forward to get updated.
